name: Build and Release6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 7.0.x

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Setup Windows 10 SDK Action
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 18362
      
      - name: Build
        run: |
          dotnet restore
          msbuild /t:build /p:Platform=x64 /p:Configuration=Release /p:AppxBundlePlatforms="x64" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Release /p:PackageCertificateKeyFile=D:\a\idkrs\idkrs\src\BiliLite.UWP\App_TemporaryKey.pfx /p:AppxPackageDir=D:\a\idkrs\idkrs\output\bin

      - name: Upload
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "test"
          path: D:\a\idkrs\idkrs\output\
