name: Build and Release6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: .NET Restore
        uses: zyactions/dotnet-restore@v1.0.1

      - name: Setup Windows 10 SDK Action
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 18362
      
      - name: Build
        run: |
          dotnet build -c Release -p:Platform=x64 /p:AppxBundlePlatforms="x64" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Release /p:PackageCertificateKeyFile=D:\a\idkrs\idkrs\src\BiliLite.UWP\App_TemporaryKey.pfx /p:AppxPackageDir=D:\a\idkrs\idkrs\output\bin

      - name: Upload
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "test"
          path: D:\a\idkrs\idkrs\output\
